# Generated by Django 6.0.3 on 2026-04-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_link_portfolio_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.CharField(default='General', max_length=50),
            preserve_default=False,
        ),
    ]
